### ISSUE TITLE
Markdown render with newline: behavior different to the GFM

### ISSUE THREAD

**Issue by huan** [OpenSourceWin/OpenSourceWin.github.io#40]
The below screenshot shows that the badges are rendered vertically (newline added) instead of in the same line:

<img width="965" alt="image" src="https://user-images.githubusercontent.com/1361891/157351098-fd03d126-7db8-4a77-9848-feff5be08eee.png">

The markdown source code is:

```markdown
[![NPM Version](https://img.shields.io/npm/v/wechaty?color=brightgreen)](https://www.npmjs.com/package/wechaty)
[![Downloads](https://img.shields.io/npm/dm/wechaty.svg?style=flat-square)](https://www.npmjs.com/package/wechaty)
[![GitHub stars](https://img.shields.io/github/stars/wechaty/wechaty.svg?label=github%20stars)](https://github.com/wechaty/wechaty)
[![Docker Pulls](https://img.shields.io/docker/pulls/wechaty/wechaty.svg?maxAge=2592000)](https://hub.docker.com/r/wechaty/wechaty/)
[![ES Modules](https://img.shields.io/badge/ES-Modules-orange)](https://github.com/Chatie/tsconfig/issues/16)
```

If we render them in the issue with the [GitHub Flavored Markdown (GFM)](https://github.github.com/gfm/) in line, they are in the same line:

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1361891/157351549-099c40ba-f609-426e-9667-da8b3072f535.png">

> See: https://github.com/OpenSourceWin/OpenSourceWin.github.io/blob/main/source/huan/index.md

I'd like to ask for GFM support for OpenSource.win system because it will be very convenient if we can be consist with the markdown syntax semantic.

**Comment by sy-records** [comment]
hexo will add a `<br>` after rendering

**Comment by huan** [comment]
Got it, thanks for the fix for my badges!
